### ISSUE TITLE
Clear extra commands

### ISSUE THREAD

**Issue by s7arborne** [acm-iem/Dseized-Bot#26]
Some commands are not needed anymore so I want someone to remove them

**Comment by theritwikkundu** [comment]
May I take up this issue?

**Comment by manishrajkhan** [comment]
Can I work on that?

**Comment by s7arborne** [comment]
Yeah sure I'm assigning both of you

**Comment by s7arborne** [comment]
Well done @theritwikkundu and @manishrajkhan
