### ISSUE TITLE
Readme Update 

### ISSUE THREAD

**Issue by itisaby** [acm-iem/Dseized-Bot#5]
Update Readme.md so that anyone can understand where to contribute.

**Comment by siddharth1704** [comment]
Can you assign me to this issue

**Comment by itisaby** [comment]
ok go ahead

**Comment by siddharth1704** [comment]
Can you provide the basic procedure for contribution in your repo if there are some rules  or just  i have to add if you find any issue kindky rasie it and genrate its pr?

**Comment by itisaby** [comment]
It will be updated by tonight stay tuned :)

**Comment by siddharth1704** [comment]
ok

**Comment by Anik-Sur** [comment]
#8 
Check it out !

**Comment by s7arborne** [comment]
well done @Anik-Sur
